version: '3.8'

services:
  # Next.js Frontend
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - app-network

  # Python AI API
  python-api:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
      - DEBUG=False
      - API_HOST=0.0.0.0
      - API_PORT=8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # Hono Backend Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PYTHON_API_URL=http://python-api:8000
      - PORT=4000
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT:-}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID:-}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY:-}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      python-api:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
