version: '3.8'

services:
  # Next.js Frontend (Development)
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - python-api
    networks:
      - app-network

  # Python AI API (Development)
  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
      - DEBUG=True
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./python-api:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
